# Generated by Django 5.0.2 on 2024-02-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_rename_clientes_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
