# Generated by Django 5.0.2 on 2024-04-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
