# Generated by Django 5.0.2 on 2024-04-01 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_produto_preco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco',
            new_name='price',
        ),
    ]
